# Generated by Django 3.2.7 on 2021-09-13 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('MemberID', models.AutoField(primary_key=True, serialize=False)),
                ('MemberName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('TaskID', models.AutoField(primary_key=True, serialize=False)),
                ('TaskName', models.CharField(max_length=50)),
                ('MemberAllocated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.members')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=50)),
                ('Budget', models.IntegerField()),
                ('DueBy', models.DateField()),
                ('MemberAllocated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.members')),
                ('ProjectCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.categories')),
            ],
        ),
    ]
